### ISSUE TITLE
ENS as Corp Identifier System

### ISSUE THREAD

**Issue by humbitious** [ethereum-oasis/baseline-roadmap#63] opened 2020-05-25 15:40 UTC

**Comment by brantlymillegan** [comment] 2020-05-25 23:35
Thanks John. Here’s an initial write-up of some ideas to get the discussion going.

ENS is a UI feature essential for **usability** and **security**.

It helps with **usability** because human readable names are easier for humans to recognize than computer generated identifiers. This means a wider range of humans can use the system.

It helps with **security** because it’s easier for a human to correctly type in and confirm a human readable name as the correct recipient than it is with a computer generated identifier. The security benefit increases further when combined with a Baseline-human-curated registry of ENS names confirmed to be owned by their common sense owners, with checks based on this registry built into the Baseline user client UI.

**Use Cases**
- A Baseline user needs to send ETH to another Baseline user (or otherwise interact with an EOA or contract). The first user types in the ENS name of the second user. Their client checks with the verified Baseline registry that the name is on the list and is owned by the company they are intending to be interacting with.

- A Baseline user is looking at a list of Ethereum transactions and contract interaction events. The client UI uses ENS to display the associated ENS name with every EOA or contract address for easy reading.

**Names**
The native top-level domain (TLD; or domain suffix, e.g. “.COM”) of ENS is .ETH. The .ETH TLD is not in the ICANN managed DNS root and has the full security and technological benefits of a blockchain-based naming system.

ENS is also integrating the DNS namespace to work on ENS. This means that if you own a domain on DNS, you will be able to use it on ENS. This is already true of .XYZ names and a few other DNS TLDs, but we’ll be rolling out support for nearly the entire DNS name space soon (e.g. .COM, .ORG, .IO, et al). DNS names can resolve all of the same things as .ETH, but since their ownership always follows the DNS version, the security for the ownership on DNS is the same for ownership of the ENS version (this has pros and cons).

This means that Baseline users have a choice: They could use a .ETH name (e.g. microsoft.eth), or a DNS name they already own (e.g. microsoft.com).

Since each name can have subdomains, each company would only necessarily need one name. For example, if Microsoft had microsoft.eth, they could create the subdomains invoice.microsoft.eth, wallet.microsoft.eth, blockchain.microsoft.eth, et al.
To save further on costs and to keep better control of names used on Baseline, Baseline could acquire a short name like bsl.eth and then issue all of their users subdomains off of that, e.g. microsoft.bsl.eth; and then users could then issue further subdomains from that, e.g. wallet.microsoft.bsl.eth.

**Data that can be named**
Ultimately, you can store any information you want in a name’s ENS records. Meaning, if a Baseline user has a special kind of data they want to use ENS to name, they can do that, and without asking anyone for permission, as ENS has a built in method for the creation of new record types.

Standard record types includes Address (for an Ethereum address, of an EOA or contract), Other Addresses (any other cryptocurrency addresses, e.g. BTC, LTC, et al, as many as you'd like), Content (IPFS hash, Swarm hash, Tor .onion address), Text records (for the creation of new records, as well as a few standard text record types such as email, URL, Twitter account, et al), and DNS records (currently unused). To see an example of an ENS name with all of our standard record types, see the ENS records for [brantly.xyz](https://app.ens.domains/name/brantly.xyz).

ENS also has reverse resolution functionality, in which one can associate an Ethereum address with an ENS name. This makes it so that if you are displaying Ethereum addresses in your UI, you can look up to see if there’s an ENS name associated with it and display that instead for easier readability.

My guess would be that the most commonly used record would be the Address record, whether it’s for sending ETH or Ethereum-based tokens to an EOA, or for interacting with a contract.

**Cost**
The monetary cost of using ENS is low. Most .ETH names cost $5 a year (note that you can have unlimited subdomains on any .ETH domain with no annual cost), and there is no annual cost to using a DNS domain on ENS.

The resolution of data has no cost, since it’s simply reading off of the Ethereum blockchain.

Setting and editing ENS records has a small cost, usually around $0.01 - $0.04 per change. This is not part of the ENS protocol but is simply the Ethereum network transaction fee. This is because records are stored on the Ethereum blockchain and making a chance to the Ethereum state costs an Ethereum transaction fee.

**Curated registry**
This is the only part of what I’ve written so far that doesn’t already exist. Everything else already exists and is working on Ethereum mainnet, available for Baseline users to start using anytime.

I’m imagining either a company or a Baseline group that would verify which company uses what names and for what purposes and then make that registry publicly available. The registry could be stored on chain (ENS itself could be used for this registry), or it could be stored off chain and available via an API (there are many ways this could be accomplished). When a user types in a name, their client UI could check the registry API and display some sort of notice verifying who the name belongs to so that the user can quickly and easily verify they are using the correct name.

This service could also serve the Ethereum community outside of Baseline (revenue opportunity?).

**Why use ENS and not a centralized Baseline phonebook?**
There are two reasons Baseline should use ENS rather than a centrally controlled phonebook:

First, future-proofing: ENS is a widely used standard in Ethereum space (more than 140 services have it integrated and growing fast), and Baseline users should plan for a future now in which they are more embedded in the greater Ethereum space. It also means that Baseline users won’t have the cost of building a centralized phonebook now only to abandon it for ENS later.

Second, unique capabilities: Because ENS names are smart-contract objects on Ethereum, they can interact with other smart contracts, allowing for functionality you can’t get any other way. This includes things like: names managed by smart-contracts, names automatically doing things based on other smart-contract events, et al.

**Comment by sambacha** [comment] 2020-06-09 12:30
Honestly, this should be more of an integration with LEI, Legal Entity Identifiers as its a regulatory compliance thing and the data is accessible already. 

Here is the golden master records for GLEIF: https://www.gleif.org/en/lei-data/gleif-golden-copy/download-the-golden-copy#/

It is about 2gigabytes worth of corporate records, including subsidiary information and owner information. 

For example, our corporate LEI is: 254900C9UJMDGJ0ILK56

You can implement this with a service protocol like a dynamic delegation discovery system as its a serialized format. Read more here: https://tools.ietf.org/html/rfc3401

**Comment by brantlymillegan** [comment] 2020-06-09 21:50
@sambacha Sounds great. If I'm understanding you correctly, yes someone could easily store a LEI in an ENS record. Right now, it could be easily done as a text record (could use "lei" or similar for the text record key).

**Comment by sambacha** [comment] 2020-06-10 00:14
Yes, the good thing as well is we already have a pristine record of registered companies using it, they could additionally do the reverse and use their domain name to register a .eth account which then would enable them to use that point of registration to associate other addresses, etc. 

Think of LEI as like an IBAN, but global. Also an LEI is not expensive infact I know someone on telegram who has an LEI accredited reseller, about $60-75 a yr.

**Comment by humbitious** [comment] 2020-06-21 03:01
Looking forward to reviewing at next SSC

**Comment by juanfranblanco** [comment] 2020-06-22 15:57
The only issue I see here is that domains have been already purchased for certain companies, but we could have a generic subdomain ie (xxx.baseline.eth) for all companies may don't want to or cannot purchase their own domain. The great thing about ENS, is that Baseline as the root owner, can give full control to those companies of their own domain and capability to create any subdomains.

**Comment by brantlymillegan** [comment] 2020-06-22 19:09
> The only issue I see here is that domains have been already purchased for certain companies, but we could have a generic subdomain ie (xxx.baseline.eth) for all companies may don't want to or cannot purchase their own domain. The great thing about ENS, is that Baseline as the root owner, can give full control to those companies of their own domain and capability to create any subdomains.

Yes if you read the "Names" section, you'll see the options, including that, but also some other ones. E.g., people can use the DNS names they already have (e.g. microsoft.org) with ENS.

**Comment by danielnorkin** [comment] 2021-02-03 21:47
@bradleyjw @brantlymillegan - as per the SSC call on 2/1/21 I'm checking on the status of this Epic. Let me know if you have any updates. If not, please close this Epic.

**Comment by brantlymillegan** [comment] 2021-02-05 03:56
@danielnorkin I don't have any more updates. Not really sure what I should be doing here. I still think Baseline should be using ENS since ENS is widely used in the blockchain space.

**Comment by bradleyjw** [comment] 2021-02-05 15:09
I agree with @brantlymillegan that the business directory should be based around ENS. Thanks!

**Closed by bradleyjw** 2021-02-05 15:09 UTC
Labels: Epic
